export { Hero } from "./hero";
export { About } from "./about";
export { Events } from "./events";
export { Speakers } from "./speakers";
export { Schedule } from "./schedule";
export { Sponsors } from "./sponsors";
export { Gallery } from "./gallery";
export { Faqs } from "./faqs";
export { RegisterCta } from "./register-cta";
