// Photos for the gallery

export const galleryPhotos = [
  {
    src: "/images/gallery/d1-team-on-stage.webp",
    reel: "/images/gallery/d1-team-on-stage-reel.webp",
    thumb: "/images/gallery/d1-team-on-stage-thumb.webp",
    alt: "Students applauding on stage around a low table while two guests cut a cake, under a projected IEEE Day 2025 title slide, with large blue IEEE DTU letters along the stage front.",
    focal: "50% 45%",
    width: 1600,
    height: 1205,
  },
  {
    src: "/images/gallery/d1-ieee-dtu-letters.webp",
    reel: "/images/gallery/d1-ieee-dtu-letters-reel.webp",
    thumb: "/images/gallery/d1-ieee-dtu-letters-thumb.webp",
    alt: "A dozen students standing in a line on an auditorium stage behind free-standing blue letters spelling IEEE DTU.",
    focal: "50% 45%",
    width: 1600,
    height: 1200,
  },
  {
    src: "/images/gallery/d1-crowd-on-steps.webp",
    reel: "/images/gallery/d1-crowd-on-steps-reel.webp",
    thumb: "/images/gallery/d1-crowd-on-steps-thumb.webp",
    alt: "A large group photo of around seventy attendees in black event t-shirts, standing and seated along the edge of an auditorium stage above rows of empty green seats.",
    focal: "50% 28%",
    width: 1600,
    height: 1200,
  },
  {
    src: "/images/gallery/d1-organising-team.webp",
    reel: "/images/gallery/d1-organising-team-reel.webp",
    thumb: "/images/gallery/d1-organising-team-thumb.webp",
    alt: "The organising team in matching black polo shirts arranged on the steps of a campus building, with a faculty member in a light blue shirt standing in front.",
    focal: "50% 32%",
    width: 1600,
    height: 1200,
  },
  {
    src: "/images/gallery/d2-ieee-cup-wall.webp",
    reel: "/images/gallery/d2-ieee-cup-wall-reel.webp",
    thumb: "/images/gallery/d2-ieee-cup-wall-thumb.webp",
    alt: "Red and white plastic cups wedged into a whiteboard frame to spell out IEEE as a pixel-style mosaic.",
    focal: "50% 45%",
    width: 1600,
    height: 1200,
  },
  {
    src: "/images/gallery/d2-team-in-blazers.webp",
    reel: "/images/gallery/d2-team-in-blazers-reel.webp",
    thumb: "/images/gallery/d2-team-in-blazers-thumb.webp",
    alt: "Students in formal blazers and white shirts with event lanyards standing in front of a wall-mounted screen showing the round's rules, one of them reading from a phone.",
    focal: "50% 45%",
    width: 1600,
    height: 1200,
  },
  {
    src: "/images/gallery/d2-workshop.webp",
    reel: "/images/gallery/d2-workshop-reel.webp",
    thumb: "/images/gallery/d2-workshop-thumb.webp",
    alt: "A classroom session in progress: participants working at laptops on wooden benches while two organisers with lanyards check phones beside them, a slide headed Ctrl Alt Design on the screen behind.",
    focal: "50% 45%",
    width: 1600,
    height: 1200,
  },
  {
    src: "/images/gallery/d3-team-with-banner.webp",
    reel: "/images/gallery/d3-team-with-banner-reel.webp",
    thumb: "/images/gallery/d3-team-with-banner-thumb.webp",
    alt: "A long line of students and faculty in a sunlit campus courtyard, each holding a folder, in front of an IEEE GTBIT SB banner reading Advancing Technology for Humanity.",
    focal: "50% 45%",
    width: 1600,
    height: 1067,
  },
  {
    src: "/images/gallery/d3-award-winners.webp",
    reel: "/images/gallery/d3-award-winners-reel.webp",
    thumb: "/images/gallery/d3-award-winners-thumb.webp",
    alt: "Six winners holding framed certificates and canvas goodie bags around a small gold trophy, photographed in front of the IEEE GTBIT SB banner.",
    focal: "50% 45%",
    width: 1600,
    height: 1067,
  },
  {
    src: "/images/gallery/d3-volunteers.webp",
    reel: "/images/gallery/d3-volunteers-reel.webp",
    thumb: "/images/gallery/d3-volunteers-thumb.webp",
    alt: "Volunteers in black event t-shirts and lanyards gathered on a paved campus courtyard beside a basketball hoop, with an academic block and trees behind them.",
    focal: "50% 45%",
    width: 1600,
    height: 1067,
  },
];

// Label for gallery
export const galleryLabel = "IEEE Day 2025";
