/**
 * Team data — the council and committee leads.
 *
 * Each entry: [image, name, role, instagramUrl | null, linkedinUrl]
 * Images live in /public/images/council/
 */

export const teamSection = {
  label: "THE PEOPLE BEHIND THE WORK",
  heading: "Meet the",
  headingAccent: "team.",
};

export const teamMembers = [
  {
    id: "rudit-madaan",
    image: "rudit_madaan.png",
    name: "Rudit Madaan",
    role: "Chairperson",
    instagram: "https://www.instagram.com/rudit_madaan/",
    linkedin: "https://www.linkedin.com/in/rudit-madaan/",
  },
  {
    id: "bhavit-jain",
    image: "bhavit_jain.jpeg",
    name: "Bhavit Jain",
    role: "Vice Chairperson",
    instagram: "https://www.instagram.com/jainbhavit2018/",
    linkedin: "https://www.linkedin.com/in/jainbhavit2018/",
  },
  {
    id: "jitendra-kumar-singh",
    image: "jitendra_kumar_singh.jpg",
    name: "Jitendra Kumar Singh",
    role: "General Secretary",
    instagram: "https://www.instagram.com/18jitendra_/",
    linkedin: "https://www.linkedin.com/in/jitendra-kumar-singh-878b2a286/",
  },
  {
    id: "dhruv-chiripal",
    image: "dhruv_chiripal.jpg",
    name: "Dhruv Chiripal",
    role: "Joint Secretary",
    instagram: "https://www.instagram.com/dhruv.chiripal/",
    linkedin: "https://www.linkedin.com/in/dhruv-chiripal/",
  },
  {
    id: "aditya-tiwari",
    image: "aditya_tiwari.jpg",
    name: "Aditya Tiwari",
    role: "Joint Secretary",
    instagram: "https://www.instagram.com/adityatiwari_in/",
    linkedin: "https://www.linkedin.com/in/aditya-tiwari-784517279/",
  },
  {
    id: "ashutosh-kumar-mishra",
    image: "ashutosh_kumar_mishra.webp",
    name: "Ashutosh Kumar Mishra",
    role: "Treasurer",
    instagram: "https://www.instagram.com/ashutosh_mishr_/",
    linkedin: "https://www.linkedin.com/in/ashutosh-mishra-3843953ab/",
  },
  {
    id: "mridul-mor-webmaster",
    image: "mridul_mor.jpeg",
    name: "Mridul Mor",
    role: "Webmaster",
    instagram: "https://www.instagram.com/_mridul_mor/",
    linkedin: "https://www.linkedin.com/in/mridul-mor/",
  },
  {
    id: "jahan-sharma",
    image: "jahan_sharma.jpeg",
    name: "Jahan Sharma",
    role: "Chairperson, CS",
    instagram: null,
    linkedin: "https://www.linkedin.com/in/jahansharma/",
  },
  {
    id: "unnat-agarwal",
    image: "unnat_agarwal.jpg",
    name: "Unnat Agarwal",
    role: "Vice Chairperson, CS",
    instagram: "https://www.instagram.com/_unnat_7779/",
    linkedin: "https://www.linkedin.com/in/unnat7779/",
  },
  {
    id: "shashwat-jha",
    image: "shashwat_jha.jpg",
    name: "Shashwat Jha",
    role: "Chairperson, PES-IAS",
    instagram: null,
    linkedin: "https://www.linkedin.com/in/shashwatjha26/",
  },
  {
    id: "shreyans-jain",
    image: "shreyans_jain.jpeg",
    name: "Shreyans Jain",
    role: "Vice Chairperson, PES-IAS",
    instagram: "https://www.instagram.com/shreyansj28/",
    linkedin: "https://www.linkedin.com/in/shreyans-jain-7925a7326/",
  },
  {
    id: "srijoni-das",
    image: "srijoni_das.jpeg",
    name: "Srijoni Das",
    role: "Chairperson, CASS",
    instagram: "https://www.instagram.com/srijo8031/",
    linkedin: "https://www.linkedin.com/in/srijoni-das-13a8b1280/",
  },
  {
    id: "sneha-meerwal",
    image: "sneha_meerwal.png",
    name: "Sneha Meerwal",
    role: "Vice Chairperson, CASS",
    instagram: "https://www.instagram.com/snehameerwal/",
    linkedin: "https://www.linkedin.com/in/sneha-meerwal-38926a300/",
  },
  {
    id: "shraddha-singh",
    image: "shraddha_singh_2.jpeg",
    name: "Shraddha Singh",
    role: "Chairperson, WIE",
    instagram: "https://www.instagram.com/shraddha_singh05/",
    linkedin: "https://www.linkedin.com/in/shraddha-singh-29b3a528a/",
  },
  {
    id: "roshan-beja",
    image: "roshan_beja.jpg",
    name: "Roshan Beja",
    role: "Vice Chairperson, WIE",
    instagram: "https://www.instagram.com/roshan_beja/",
    linkedin: "https://www.linkedin.com/in/roshankumarbeja/",
  },
  {
    id: "mridul-mor-membership-development",
    image: "mridul_mor.jpeg",
    name: "Mridul Mor",
    role: "Head of Membership Development",
    instagram: "https://www.instagram.com/_mridul_mor/",
    linkedin: "https://www.linkedin.com/in/mridul-mor/",
  },
  {
    id: "bhavya-agarwal",
    image: "bhavya_agarwal.jpg",
    name: "Bhavya Agarwal",
    role: "Head of Corporate Affairs",
    instagram: "https://www.instagram.com/bhavyaa.ag/",
    linkedin: "https://www.linkedin.com/in/bhavya-agarwal-6733262a3/",
  },
  {
    id: "yuvraj-malik",
    image: "yuvraj_malik.jpeg",
    name: "Yuvraj Malik",
    role: "Head of Hospitality",
    instagram: "https://www.instagram.com/yuvrajmalik2005/",
    linkedin: "https://www.linkedin.com/in/yuvrajmalik2005/",
  },
  {
    id: "harshit-shakya",
    image: "harshit_shakya.jpeg",
    name: "Harshit Shakya",
    role: "Head of Logistics",
    instagram: "https://www.instagram.com/harshitshakya50/",
    linkedin: "https://www.linkedin.com/in/harshit-shakya-2b65b7288/",
  },
  {
    id: "abhinay-sahai",
    image: "abhinay_sahai.jpg",
    name: "Abhinay Sahai",
    role: "Head of Public Relations",
    instagram: "https://www.instagram.com/abhinay_sahai_/",
    linkedin: "https://www.linkedin.com/in/abhinay-sahai-30790628b/",
  },
  {
    id: "himanshu-yadav",
    image: "himanshu_yadav.jpeg",
    name: "Himanshu Yadav",
    role: "Head of Publications",
    instagram: "https://www.instagram.com/himanshu.yadv_/",
    linkedin: "https://www.linkedin.com/in/him-y/",
  },
  {
    id: "tarush-sonakya",
    image: "tarush_sonakya.jpg",
    name: "Tarush Sonakya",
    role: "Head of Technical Affairs",
    instagram: "https://www.instagram.com/anonimbus31337/",
    linkedin: "https://www.linkedin.com/in/tarush-sonakya/",
  },
];

export const gtbitTeam = [
  {
    id: "gurasees-singh",
    image: "Gurasees Singh - Treasurer and Student Advisor.jpg",
    name: "Gurasees Singh",
    role: "Treasurer and Student Advisor",
    instagram: null,
    linkedin: null,
  },
  {
    id: "gurprajas-kaur-saluja",
    image: "Gurprajas Kaur Saluja - Chairperson.png",
    name: "Gurprajas Kaur Saluja",
    role: "Chairperson",
    instagram: null,
    linkedin: null,
  },
  {
    id: "gurpratit-kaur-saluja",
    image: "Gurpratit Kaur Saluja - WIE AG Chairperson.png",
    name: "Gurpratit Kaur Saluja",
    role: "WIE AG Chairperson",
    instagram: null,
    linkedin: null,
  },
  {
    id: "Maiesha-Mehra",
    image: "Maiesha Mehra - General Secretary.png",
    name: "Maiesha Mehra",
    role: "General Secretary",
    instagram: null,
    linkedin: null,
  },
  {
    id: "Nakul-Chadda",
    image: "Nakul Chadda - Joint Secretary.png",
    name: "Nakul Chadda",
    role: "Joint Secretary",
    instagram: null,
    linkedin: null,
  },
  {
    id: "Prathamjot-Singh-Bharaj",
    image: "Prathamjot Singh Bharaj - Vice Chairperson.png",
    name: "Prathamjot Singh Bharaj",
    role: "Vice Chairperson",
    instagram: null,
    linkedin: null,
  },
  {
    id: "Ratti-Noor-Singh",
    image: "Ratti Noor Singh - CS Chapter Chairperson.png",
    name: "Ratti Noor Singh",
    role: "CS Chapter Chairperson",
    instagram: null,
    linkedin: null,
  },
]
